[package]
name = "frunk-enum-derive"
version = "0.1.0"
authors = ["Andy Caldwell <andrew.caldwell@metaswitch.com>"]
edition = "2018"
publish = ["metaswitch"]
description = "Derive macros to implement the frunk::LabelledGeneric trait on enums"
documentation = "https://docsrs.datcon.co.uk/crate/frunk-enum-derive"
repository = "https://git.datcon.co.uk/amc/frunk-enum"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.29", features = ["full"] }
proc-macro2 = "0.4.27"
quote = "0.6.11"
itertools = "0.8.0"
frunk_proc_macro_helpers = "0.0.3"
